export interface Spell {
    id: string;
    name: string;
    icon: string;
    apCost: number;
    range: number;
    minRange?: number;
    damage: number;
    description: string;
    type: "melee" | "ranged" | "magic";
    effect?: string;
    duration?: number;
    aoeShape?: "circle" | "line" | "cone";
    aoeRadius?: number;
}

export const PLAYER_SPELLS: Spell[] = [
    // Base class spells
    {
        id: "slash",
        name: "Slash",
        icon: "icon_slash",
        apCost: 1,
        range: 1,
        damage: 3,
        description: "Basic melee attack",
        type: "melee",
    },
    {
        id: "power_strike",
        name: "Power Strike",
        icon: "icon_power_strike",
        apCost: 2,
        range: 1,
        damage: 5,
        description: "Powerful melee attack",
        type: "melee",
    },
    {
        id: "arrow_shot",
        name: "Arrow Shot",
        icon: "icon_arrow_shot",
        apCost: 1,
        range: 3,
        minRange: 2,
        damage: 2,
        description: "Basic ranged attack",
        type: "ranged",
    },
    {
        id: "bone_piercer",
        name: "Bone Piercer",
        icon: "icon_bone_piercer",
        apCost: 2,
        range: 4,
        minRange: 2,
        damage: 3,
        description: "Fires a sharp bone that pierces foes.",
        type: "ranged",
    },
    {
        id: "magic_missile",
        name: "Magic Missile",
        icon: "icon_magic_missile",
        apCost: 2,
        range: 4,
        minRange: 2,
        damage: 4,
        description: "Magical ranged attack",
        type: "magic",
    },
    {
        id: "fireball",
        name: "Fireball",
        icon: "icon_fire_ball",
        apCost: 3,
        range: 3,
        minRange: 2,
        damage: 6,
        description: "Powerful fire spell",
        type: "magic",
    },

    // Artifact spells - Warrior
    {
        id: "whirlwind",
        name: "Whirlwind",
        icon: "icon_power_strike",
        apCost: 3,
        range: 1,
        damage: 4,
        description: "Spin attack hitting all adjacent enemies",
        type: "melee",
        aoeShape: "circle",
        aoeRadius: 1,
    },
    {
        id: "shield_bash",
        name: "Shield Bash",
        icon: "icon_slash",
        apCost: 2,
        range: 2,
        damage: 3,
        description: "Charge forward and bash enemies, can move through them",
        type: "melee",
    },
    {
        id: "life_steal",
        name: "Life Steal",
        icon: "icon_power_strike",
        apCost: 2,
        range: 1,
        damage: 4,
        description: "Attack that heals you for half the damage dealt",
        type: "melee",
        effect: "life_steal",
    },
    {
        id: "crushing_blow",
        name: "Crushing Blow",
        icon: "icon_power_strike",
        apCost: 3,
        range: 1,
        damage: 5,
        description: "Powerful attack that stuns the target for 1 turn",
        type: "melee",
        effect: "stun",
        duration: 1,
    },
    {
        id: "battle_roar",
        name: "Battle Roar",
        icon: "icon_slash",
        apCost: 2,
        range: 2,
        damage: 1,
        description: "Terrifying roar that weakens all nearby enemies",
        type: "melee",
        aoeShape: "circle",
        aoeRadius: 2,
        effect: "weaken",
        duration: 3,
    },
    {
        id: "earthquake",
        name: "Earthquake",
        icon: "icon_power_strike",
        apCost: 4,
        range: 0,
        damage: 3,
        description: "Slam the ground, damaging all enemies on the battlefield",
        type: "melee",
        aoeShape: "circle",
        aoeRadius: 10,
        effect: "knockdown",
    },

    // Artifact spells - Ranger
    {
        id: "precise_shot",
        name: "Precise Shot",
        icon: "icon_arrow_shot",
        apCost: 2,
        range: 6,
        minRange: 3,
        damage: 5,
        description: "Long-range shot with increased accuracy and damage",
        type: "ranged",
    },
    {
        id: "explosive_arrow",
        name: "Explosive Arrow",
        icon: "icon_bone_piercer",
        apCost: 3,
        range: 4,
        minRange: 2,
        damage: 3,
        description: "Arrow that explodes on impact, damaging nearby enemies",
        type: "ranged",
        aoeShape: "circle",
        aoeRadius: 1,
    },
    {
        id: "shadow_step",
        name: "Shadow Step",
        icon: "icon_arrow_shot",
        apCost: 1,
        range: 4,
        damage: 0,
        description: "Teleport to target location and gain stealth",
        type: "ranged",
        effect: "teleport_stealth",
    },
    {
        id: "wind_dash",
        name: "Wind Dash",
        icon: "icon_bone_piercer",
        apCost: 1,
        range: 3,
        damage: 2,
        description:
            "Dash through enemies, dealing damage and gaining extra movement",
        type: "ranged",
        effect: "dash_movement",
    },
    {
        id: "mark_target",
        name: "Mark Target",
        icon: "icon_arrow_shot",
        apCost: 1,
        range: 5,
        damage: 0,
        description:
            "Mark an enemy, making it take 50% more damage from all sources",
        type: "ranged",
        effect: "vulnerability",
        duration: 4,
    },
    {
        id: "summon_wolf",
        name: "Summon Wolf",
        icon: "icon_bone_piercer",
        apCost: 3,
        range: 2,
        damage: 0,
        description: "Summon a wolf ally that fights alongside you for 3 turns",
        type: "ranged",
        effect: "summon_ally",
        duration: 3,
    },

    // Artifact spells - Mage
    {
        id: "ice_shard",
        name: "Ice Shard",
        icon: "icon_magic_missile",
        apCost: 2,
        range: 4,
        minRange: 1,
        damage: 3,
        description: "Ice projectile that slows enemies",
        type: "magic",
        effect: "slow",
        duration: 2,
    },
    {
        id: "chain_lightning",
        name: "Chain Lightning",
        icon: "icon_fire_ball",
        apCost: 3,
        range: 3,
        minRange: 1,
        damage: 4,
        description: "Lightning that jumps between enemies",
        type: "magic",
        aoeShape: "line",
        aoeRadius: 2,
    },
    {
        id: "heal",
        name: "Heal",
        icon: "icon_magic_missile",
        apCost: 2,
        range: 0,
        damage: -6,
        description: "Restore health to yourself",
        type: "magic",
        effect: "heal_self",
    },
    {
        id: "magic_shield",
        name: "Magic Shield",
        icon: "icon_fire_ball",
        apCost: 2,
        range: 0,
        damage: 0,
        description:
            "Create a barrier that absorbs the next 8 points of damage",
        type: "magic",
        effect: "shield",
        duration: 5,
    },
    {
        id: "mind_control",
        name: "Mind Control",
        icon: "icon_magic_missile",
        apCost: 3,
        range: 3,
        damage: 0,
        description:
            "Control an enemy, making them attack their allies for 2 turns",
        type: "magic",
        effect: "charm",
        duration: 2,
    },
    {
        id: "elemental_blast",
        name: "Elemental Blast",
        icon: "icon_fire_ball",
        apCost: 4,
        range: 4,
        minRange: 1,
        damage: 6,
        description:
            "Devastating blast that randomly applies fire, ice, or lightning effects",
        type: "magic",
        aoeShape: "circle",
        aoeRadius: 1,
        effect: "random_elemental",
    },
];

