/**
 * Mage Artifacts - Magic and spellcasting focused artifacts
 * These artifacts provide spells and abilities that emphasize magical power,
 * elemental control, arcane knowledge, and mystical effects.
 */

import { Artifact } from "../../classes/Artifact";

export const MAGE_ARTIFACTS: Artifact[] = [
    // ===== ELEMENTAL ARTIFACTS =====

    {
        id: "staff_of_frost",
        name: "Staff of Eternal Frost",
        description: "A crystalline staff that commands ice and cold",
        icon: "icon_magic_missile",
        classId: "mage",
        rarity: "rare",
        spell: {
            id: "ice_shard",
            name: "Ice Shard",
            icon: "icon_magic_missile",
            apCost: 2,
            range: 4,
            minRange: 1,
            damage: 3,
            description: "Ice projectile that slows enemies",
            type: "magic",
            effect: "slow",
            duration: 2,
        },
    },
    {
        id: "orb_of_lightning",
        name: "Orb of Lightning",
        description: "A crackling orb that channels the power of storms",
        icon: "icon_fire_ball",
        classId: "mage",
        rarity: "rare",
        spell: {
            id: "chain_lightning",
            name: "Chain Lightning",
            icon: "icon_fire_ball",
            apCost: 3,
            range: 3,
            minRange: 1,
            damage: 4,
            description: "Lightning that jumps between enemies",
            type: "magic",
            aoeShape: "line",
            aoeRadius: 2,
        },
    },
    {
        id: "sphere_of_elements",
        name: "Sphere of Elemental Chaos",
        description: "A swirling orb containing the fury of all elements",
        icon: "icon_fire_ball",
        classId: "mage",
        rarity: "legendary",
        spell: {
            id: "elemental_blast",
            name: "Elemental Blast",
            icon: "icon_fire_ball",
            apCost: 4,
            range: 4,
            minRange: 1,
            damage: 6,
            description:
                "Devastating blast that randomly applies fire, ice, or lightning effects",
            type: "magic",
            aoeShape: "circle",
            aoeRadius: 1,
            effect: "random_elemental",
        },
    },

    // ===== UTILITY & SUPPORT ARTIFACTS =====

    {
        id: "tome_of_healing",
        name: "Tome of Divine Healing",
        description: "An ancient book containing powerful healing magic",
        icon: "icon_magic_missile",
        classId: "mage",
        rarity: "epic",
        spell: {
            id: "heal",
            name: "Heal",
            icon: "icon_magic_missile",
            apCost: 2,
            range: 0,
            damage: -6, // Negative damage = healing
            description: "Restore health to yourself",
            type: "magic",
            effect: "heal_self",
        },
    },
    {
        id: "crystal_of_barriers",
        name: "Crystal of Arcane Barriers",
        description: "A protective crystal that creates magical shields",
        icon: "icon_fire_ball",
        classId: "mage",
        rarity: "rare",
        spell: {
            id: "magic_shield",
            name: "Magic Shield",
            icon: "icon_fire_ball",
            apCost: 2,
            range: 0,
            damage: 0,
            description:
                "Create a barrier that absorbs the next 8 points of damage",
            type: "magic",
            effect: "shield",
            duration: 5,
        },
    },
    {
        id: "wand_of_illusion",
        name: "Wand of Mind Control",
        description: "A twisted wand that bends the will of enemies",
        icon: "icon_magic_missile",
        classId: "mage",
        rarity: "rare",
        spell: {
            id: "mind_control",
            name: "Mind Control",
            icon: "icon_magic_missile",
            apCost: 3,
            range: 3,
            damage: 0,
            description:
                "Control an enemy, making them attack their allies for 2 turns",
            type: "magic",
            effect: "charm",
            duration: 2,
        },
    },

    // ===== ADDITIONAL MAGE ARTIFACTS =====

    {
        id: "arcane_focus_crown",
        name: "Crown of Arcane Focus",
        description: "A crystalline crown that amplifies magical energies",
        icon: "icon_magic_missile",
        classId: "mage",
        rarity: "epic",
        spell: {
            id: "mana_surge",
            name: "Mana Surge",
            icon: "icon_magic_missile",
            apCost: 1,
            range: 0,
            damage: 0,
            description:
                "Gain +3 AP for this turn, all spells cost +1 AP next turn",
            type: "magic",
            effect: "mana_boost_penalty",
            duration: 2,
        },
    },
    {
        id: "robe_of_stars",
        name: "Starweave Robe",
        description: "A mystical robe woven from starlight and dreams",
        icon: "icon_fire_ball",
        classId: "mage",
        rarity: "rare",
        spell: {
            id: "starfall",
            name: "Starfall",
            icon: "icon_fire_ball",
            apCost: 3,
            range: 5,
            damage: 2,
            description: "Rain stars from the sky in a large area",
            type: "magic",
            aoeShape: "circle",
            aoeRadius: 2,
            effect: "celestial_damage",
        },
    },
    {
        id: "scrying_orb",
        name: "Orb of True Sight",
        description: "A mystical orb that reveals hidden truths and weaknesses",
        icon: "icon_magic_missile",
        classId: "mage",
        rarity: "rare",
        spell: {
            id: "reveal_weakness",
            name: "Reveal Weakness",
            icon: "icon_magic_missile",
            apCost: 2,
            range: 6,
            damage: 0,
            description:
                "Reveal enemy stats and reduce their armor by 2 for 4 turns",
            type: "magic",
            effect: "analyze_weaken",
            duration: 4,
        },
    },
    {
        id: "void_gauntlets",
        name: "Gauntlets of the Void",
        description: "Dark gauntlets that channel the power of nothingness",
        icon: "icon_fire_ball",
        classId: "mage",
        rarity: "epic",
        spell: {
            id: "void_bolt",
            name: "Void Bolt",
            icon: "icon_fire_ball",
            apCost: 3,
            range: 4,
            damage: 5,
            description: "Dark magic that ignores all resistances and armor",
            type: "magic",
            effect: "true_damage",
        },
    },
    {
        id: "time_warping_amulet",
        name: "Amulet of Temporal Flux",
        description:
            "An ancient amulet that allows manipulation of time itself",
        icon: "icon_magic_missile",
        classId: "mage",
        rarity: "legendary",
        spell: {
            id: "time_stop",
            name: "Time Stop",
            icon: "icon_magic_missile",
            apCost: 4,
            range: 0,
            damage: 0,
            description:
                "Freeze time for 1 turn, gain an extra turn immediately",
            type: "magic",
            effect: "extra_turn",
        },
    },
    {
        id: "book_of_shadows",
        name: "Grimoire of Dark Knowledge",
        description: "A forbidden tome containing ancient and terrible spells",
        icon: "icon_fire_ball",
        classId: "mage",
        rarity: "epic",
        spell: {
            id: "life_drain",
            name: "Life Drain",
            icon: "icon_fire_ball",
            apCost: 3,
            range: 3,
            damage: 4,
            description: "Drain life from target, healing you for damage dealt",
            type: "magic",
            effect: "vampiric_magic",
        },
    },
];
